// Code generated by mockery v1.0.0. DO NOT EDIT.

package storage

import mock "github.com/stretchr/testify/mock"

// MockInMemoryStore is an autogenerated mock type for the InMemoryStore type
type MockInMemoryStore struct {
	mock.Mock
}

// Add provides a mock function with given fields: host, fname
func (_m *MockInMemoryStore) Add(host string, fname string) error {
	ret := _m.Called(host, fname)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(host, fname)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Pop provides a mock function with given fields:
func (_m *MockInMemoryStore) Pop() []Destination {
	ret := _m.Called()

	var r0 []Destination
	if rf, ok := ret.Get(0).(func() []Destination); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Destination)
		}
	}

	return r0
}
